version:
  class: 'piper.version.StaticVersion'
  version: '0.0.1'

envs:
  local:
    version: '0.0.1'
    class: 'piper.env.Env'

steps:
  test:
    class: 'piper.step.CommandLineStep'
    command: 'tox'
  build:
    class: 'piper.step.CommandLineStep'
    command: 'python setup.py sdist'
    depends: 'test'

jobs:
  test:
  - 'test'
  build:
  - 'build'
