version:
  class: 'piper.version.GitVersion'
  arguments: '--tags --long --dirty'

envs:
  local:
    class: 'piper.env.EnvBase'

steps:
  test:
    class: 'piper.step.CommandLineStep'
    command: 'tox'
  build:
    class: 'piper.step.CommandLineStep'
    command: 'python setup.py sdist'
    depends: 'test'

jobs:
  test:
  - 'test'
  build:
  - 'build'

db:
  host: 'sqlite:///data/piper.db'
  user:
  password:
