version: '0.0.1-alpha1'

envs:
  local:
    version: '0.0.1'
    class: 'piper.env.Env'

steps:
  test:
    version: '0.0.1'
    class: 'piper.step.Step'
    command: '/usr/bin/env python setup.py test'
  build:
    version: '0.0.1'
    class: 'piper.step.Step'
    command: '/usr/bin/env python setup.py sdist'
    depends: 'test'

jobs:
  test:
  - 'test'
  build:
  - 'build'
