version:
  class: 'piper.version.GitVersion'
  arguments: '--tags --long --dirty'

envs:
  local:
    class: 'piper.env.Env'

steps:
  test:
    class: 'piper.step.CommandLineStep'
    command: 'tox'
  lint:
    class: 'piper.step.CommandLineStep'
    command: 'flake8 -v piper/ test/'
  build:
    class: 'piper.step.CommandLineStep'
    command: 'python setup.py sdist'

jobs:
  test:
    - 'test'
  lint:
    - 'lint'
  build:
    - 'lint'
    - 'test'
    - 'build'

db:
  class: 'piper.db.SQLAlchemyDB'
  host: 'sqlite:///data/piper.db'
  user:
  password:
