version:
  class: 'piper.version.GitVersion'
  arguments: '--tags --long --dirty'

envs:
  local:
    class: 'piper.env.Env'
    requirements:
      is_not_virtual:
        reason: 'The base environment cannot run if virtualized'
        class: 'piper.prop.FacterProp'
        key: 'virtual'
        equals: 'physical'

steps:
  test:
    class: 'piper.step.CommandLineStep'
    command: 'tox'
    requirements: null
  lint:
    class: 'piper.step.CommandLineStep'
    command: 'flake8 -v piper/ test/'
    requirements: null
  build:
    class: 'piper.step.CommandLineStep'
    command: 'python setup.py sdist'
    requirements: null

pipelines:
  test:
    - 'test'
  lint:
    - 'lint'
  build:
    - 'lint'
    - 'test'
    - 'build'

db:
  class: 'piper.db.SQLAlchemyDB'
  host: 'sqlite:///data/piper.db'
  user:
  password:
